alias gst='git status -sb'
alias gba='git branch -a'
alias gco='git checkout'
alias gpo='git push origin master'
alias gpp='git push production'
alias gd='git diff'
alias gdc='git diff --cached'
alias glg='git log --all --decorate --graph --oneline --abbrev-commit'
